name: CI/CD workflow for Maven Build, Sonar Code scan and Quality gate check
 
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to build"
        required: true
        #default: "master"
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target_branch }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
 
      # Build with Maven
      - name: Build with Maven
        run: mvn clean install
 
      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=my-test-app
        env:
          SONAR_TOKEN: sqa_de170496f41c08ad99da487eb0eb2202a6f81f58
          SONAR_HOST_URL: http://100.26.36.190:9000
      - name: Display selected branch
        run: echo "Running on branch ${{ github.event.inputs.target_branch }}"
      - name: Checking context variable
        run: |
          echo "Repository name: ${{ github.repository }}"
          echo "Workflow name: ${{ github.workflow }}"
          echo "Triggered by: ${{ github.triggering_actor }}"
      # Check SonarQube Quality Gate status
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: sqa_de170496f41c08ad99da487eb0eb2202a6f81f58
          SONAR_HOST_URL: http://100.26.36.190:9000
 
      # Show the Quality Gate result
      - name: Show Quality Gate Status
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
