name: CI/CD workflow for Maven Build and Sonar Code scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=my-Java-web-app
        env:
          SONAR_TOKEN: sqa_de170496f41c08ad99da487eb0eb2202a6f81f58
          SONAR_HOST_URL: http://3.80.32.19:9000

      # Check SonarQube Quality Gate status
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: sqa_de170496f41c08ad99da487eb0eb2202a6f81f58
          SONAR_HOST_URL: http://3.80.32.19:9000

      # Show the Quality Gate result
      - name: Show Quality Gate Status
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
